### PR TITLE
Update AWS benchmarks

### PR DESCRIPTION
**Pull request by gfinol**

### CODE REVIEW

**Comment by JosepSampe** [comment]
@gfinol Do you know why the invocation starts after 10 seconds?

**Comment by gfinol** [comment]
@JosepSampe No idea. I believe I had the default settings for AWS. I'll review them and check that everything is okay.

**Comment by JosepSampe** [comment]
Just another question. The old experiments took 70 seconds to finish. The new experiments take 35 seconds to finish. Do you know why it performs 2x better? Did you use 1GB of memory for the new ones?

**Comment by gfinol** [comment]
@JosepSampe. I noticed the improvement in the flops experiment, but as I was using 1GB of memory per function, I just assumed that AWS improved their machines.

I've used the same parameters that are specified in the READMEs.  Which I believe are the ones used in the old experiments.

Flops benchmark:
```
python flops_benchmark.py --backend aws_lambda --loopcount=5 --matn=4096 --tasks=1000 --memory=1024 --outdir=aws_lambda
```

Read/Writte: 
```
python os_benchmark.py run -b aws_lambda -s aws_s3 --mb_per_file=512 --bucket_name=[my_bucket] --number=1000 --outdir=aws_s3
```

**Comment by JosepSampe** [comment]
Ok, cool! Yes, the parameters are ok, so probably they improved the amount of CPU per function by 2x

**Pull request merged**
